### ISSUE TITLE
Two different kube config users generated from one google user

### ISSUE THREAD

**Issue by Aracki** [gini/dexter#28]
Maybe we need to add the feature, that enables one google user with different credentials generate a two different users in `~/.kube/config`?

**Comment by dkerwin** [comment]
Hi Ivan,

could you please elaborate about your concrete use-case? I personally cannot think of a application that would benefit from it so I'm really curious ;-)

**Comment by Aracki** [comment]
e.g. You have two k8s clusters which you can access with the same user but different credentials.

**Comment by Aracki** [comment]
Great one @dkerwin
