### ISSUE TITLE
Missing tmpl/kube-config.yaml

### ISSUE THREAD

**Issue by phidlipus** [gini/dexter#42]
Building from freshly cloned repository failed, because of missing `tmpl/kube-config.yaml`.

How to reproduce:
```
git clone https://github.com/gini/dexter.git
cd dexter
docker run --rm --privileged \
  -v $PWD:/go/src/github.com/user/repo \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /go/src/github.com/user/repo \
  --env-file ../env-file \
  goreleaser/goreleaser release --snapshot --rm-dist
```
In the `.gitignore`, there are lines:
```
# This is required to allow goreleaser to release with different templates.
# The actual config has to be copied to the location in a prep step.
tmpl/kube-config.yaml
```

Maybe, there should be a step, during the build, where the default `kube-config.yaml` is provided, if I don't provide custom one.

**Comment by dkerwin** [comment]
Good catch. I've added a goreleaser hook to make sure that the default config is present when no other config is present in tmpl/.

**Comment by phidlipus** [comment]
@dkerwin Thanks!
