### ISSUE TITLE
Timeout too low

### ISSUE THREAD

**Issue by felixfriedrich** [gini/dexter#48]
I've ran into timeout issues, which I could fix by changing this timeout here: https://github.com/gini/dexter/blob/master/cmd/google.go#L23

I attempted to authenticate using Google like this:

```
dexter auth google \
  --client-id=${id} \
  --client-secret=${secret}
```

The error looked like this:

```
ERRO[2023-03-03T13:47:56+01:00] Failed to exchange auth code: Post "https://oauth2.googleapis.com/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Would you accept a pull request either raising the timeout or make it configurable?

**Comment by felixfriedrich** [comment]
@dkerwin This keeps happening. Not consistently, but it does.

**Comment by dkerwin** [comment]
Hey @felixfriedrich. I would totally accept a PR to fix this problem. Sorry that this keep happening for you
