### ISSUE TITLE
Unable to start dexter

### ISSUE THREAD

**Issue by nagarjunac** [gini/dexter#6]
Hi,
I have downloaded the pre built darwin package and tried to run "./dexter_darwin_amd64 --client-id=XXX --client-secret=XXX auth" command. 
I am getting the below error.
ERRO[2018-05-15T15:17:11+05:30] oauth2 configuration failed: failed to create new dexterOIDC provider: Get https://accounts.google.com/.well-known/openid-configuration: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

My internet connectivity is fine. Please help me with this.

**Comment by nagarjunac** [comment]
Sorry, it was a firewall issue.

**Comment by dkerwin** [comment]
I'm glad you were able to solve this. Feel free to get back anytime if you have questions or need support. 

Cheers!
Daniel
